# .github/workflows/github-pages.yml
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4
        
      - name: Setup Node.js environment ğŸŒ
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '18' # or your preferred Node.js version

      - name: Install dependencies ğŸ“¦
        run: npm ci


      - name: Build ğŸ—ï¸
        run: |
          REACT_APP_ACCESS_TOKEN=${{ secrets.REACT_APP_ACCESS_TOKEN }}
          # use the secret in some way during build process, e.g., pass it to a script
          npm run build --env.REACT_APP_ACCESS_TOKEN=$REACT_APP_ACCESS_TOKEN

      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./public # or wherever your built site resides
